version: '3.8'

services:
  orders-db:
    container_name: orders_database
    image: postgres:15.3
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data   # mantener la data
    ports:
      - 5437:5432                         # local/contenedor
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb

